apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-sample2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: component-sample2
    app.kubernetes.io/part-of: application-sample
  name: component-sample2
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: component-sample2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: component-sample2
    spec:
      containers:
      - image: quay.io/redhat-appstudio/sample-image@sha256:0354fa127deb6e3b93672221f6ff949087c73ca67a45bc88ddcbde6042d40a8a
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
